<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>uned_crazyflie_controllers</name>
  <version>0.0.0</version>
  <description>Controladores en C++ para el crazyflie 2.1: PID periódico (posición y velocidad angular), PID basado en eventos, predictivo generalizado y de trayectoria</description>
  <maintainer email="fjmanas@dia.uned.es">Francisco José Mañas Álvarez</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>eigen3_cmake_module</depend>
  <depend>uned_crazyflie_config</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
